[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Jayden Bulexa", email = "JaydenB0@pm.me"},
]
dependencies = [
    "watchdog>=2.2.0",
    "pyfiglet>=0.8.post1",
    "logging>=0.4.9.6",
    "loguru>=0.6.0",
]
requires-python = ">=3.11"
license = {text = "MIT"}
