version: '3.8'
networks:
  default:
    name: farm-network
    external: false

services:
  server:
    image: python:3.9.16-slim
    build:
      context: server/
      args:
        FARM_VERSION: ${FARM_VERSION}
    restart: unless-stopped
  client:
    image: python:3.9.16-slim
    build:
      context: client/
      args:
        FARM_VERSION: ${FARM_VERSION}
    restart: unless-stopped
    volumes:
      - ./client/exploits:/app/exploits